CREATE OR REPLACE WAREHOUSE ML_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE AI_ML_PROJECT;

CREATE OR REPLACE SCHEMA AI_ML_PROJECT.LOGISTICS;

USE WAREHOUSE ML_WH;
USE DATABASE AI_ML_PROJECT;
USE SCHEMA LOGISTICS;